### Atividade

Abaixo temos um pequeno script que cria um dataframe aleatório. Rode a célula abaixo, e não se preocupe em entender o que ela está fazendo. Confia no processo e responda as questões a seguir.

In [50]:
import pandas as pd
import numpy as np
np.random.seed(42)
df_3 = pd.DataFrame({"idade": np.random.randint(18, 70, 100), "salario": np.random.normal(loc=5000, scale=1200, size=100),"cidade": np.random.choice(["Porto Alegre", "Canoas", "Gravataí", "Viamão"],100)})
idx_1 = np.random.choice(df_3.index, 5, replace=False)
df_3.loc[idx_1, "idade"] *= -1
idx_2 = np.random.choice(df_3.index.difference(idx_1),10,replace=False)
df_3.loc[idx_2, "idade"] = np.nan
idx_3 = np.random.choice(df_3.index, 5, replace=False)
df_3.loc[idx_3, "salario"] *= 4
idx_4 = np.random.choice(df_3.index, 15, replace=False)
df_3.loc[idx_4, "salario"] = np.nan
df_3['salario'] = df_3['salario'].astype(str)
cidade = ["Port Algre","Porto Alegri","Cnoas","Canoass","Gravatai","Gravatí","Viamao","Viammão"]
idx_5 = np.random.choice(df_3.index, 12, replace=False)
df_3.loc[idx_5, "cidade"] = np.random.choice(cidade,len(idx_5))
idx_6 = np.random.choice(df_3.index.difference(idx_5),8,replace=False)
df_3.loc[idx_6, "cidade"] = np.nan
print(df_3.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   idade    90 non-null     float64
 1   salario  85 non-null     str
 2   cidade   92 non-null     str
dtypes: float64(1), str(2)
memory usage: 2.5 KB
None

In [51]:
df_3.head()

   idade             salario    cidade
0   56.0  2749.1878733521794    Canoas
1   69.0                 NaN  Gravataí
2  -46.0   5763.566130014205  Gravataí
3   32.0   3911.935197704084    Viamão
4   60.0   5571.251104912366    Viamão

In [5]:
df_original = df_3.copy()

In [ ]:
df = df_3

In [9]:
df_3['idade'].mean()

np.float64(39.022222222222226)

In [8]:
df_3['idade'] = df_3['idade'] + 1

In [10]:
df['idade'].mean()

np.float64(39.022222222222226)

In [11]:
df_original['idade'].mean()

np.float64(38.022222222222226)

In [12]:
df = df_original.copy()

In [15]:
df['idade'].mean()

np.float64(38.022222222222226)

### 1) Responda:
- a) Número de linhas

In [22]:
df.shape[0]
len(df)
df['idade'].size

100

- b) Número de Colunas

In [ ]:
n_colunas = df.shape[1]
df.columns.size

3

In [27]:
df

    idade             salario        cidade
0    56.0  2749.1878733521794        Canoas
1    69.0                 NaN      Gravataí
2   -46.0   5763.566130014205      Gravataí
3    32.0   3911.935197704084        Viamão
4    60.0   5571.251104912366        Viamão
..    ...                 ...           ...
95   42.0    5078.77898973347        Canoas
96   62.0   6403.049176343147  Porto Alegre
97    NaN   6047.980362907312        Viamão
98   46.0   5246.780160808004      Gravataí
99   32.0   3267.819977964514           NaN

[100 rows x 3 columns]

- c) Qual o nome das colunas?

In [29]:
nomecol = df.columns

In [32]:
for i in nomecol:
    print(f'O campo {i} tem {df[i].isnull().sum()} valores nulos.')

O campo idade tem 10 valores nulos.
O campo salario tem 15 valores nulos.
O campo cidade tem 8 valores nulos.

- d) Qual o tipo de dado de cada coluna?

In [33]:
df.dtypes

idade      float64
salario        str
cidade         str
dtype: object

In [35]:
for i in nomecol:
    print(f'O campo {i} é do tipo {df[i].dtypes}.')

O campo idade é do tipo float64.
O campo salario é do tipo str.
O campo cidade é do tipo str.

- e) Quantos valores nulos cada coluna tem?

In [36]:
for i in nomecol:
    print(f'O campo {i} tem {df[i].isnull().sum()} valores nulos.')

O campo idade tem 10 valores nulos.
O campo salario tem 15 valores nulos.
O campo cidade tem 8 valores nulos.

- f) Quais as categorias presentes no campo "cidade?

In [37]:
df['cidade'].unique()

<StringArray>
[      'Canoas',     'Gravataí',       'Viamão',        'Cnoas',
 'Porto Alegre',   'Port Algre',       'Viamao',            nan,
      'Viammão',      'Gravatí']
Length: 10, dtype: str

- g) Quantas linhas duplicadas aparecem nos dados?

In [39]:
df.duplicated().sum()

np.int64(0)

##### 2) Para cada coluna, qual o percentual de valores nulos?

(Eu perguntei percentual.)

In [41]:
nulos = df.isnull().sum()
total = len(df)
percentual = 100*nulos/total
percentual

idade      10.0
salario    15.0
cidade      8.0
dtype: float64

In [42]:
for i in nomecol:
    nulos = df[i].isnull().sum()
    total = len(df)
    percentual = 100*nulos/total
    print(f'O campo {i} tem {percentual}% de valores nulos.')

O campo idade tem 10.0% de valores nulos.
O campo salario tem 15.0% de valores nulos.
O campo cidade tem 8.0% de valores nulos.

### 3) Corrija os tipos de dado das colunas.

In [43]:
df.dtypes

idade      float64
salario        str
cidade         str
dtype: object

In [48]:
df_original.head()

   idade             salario    cidade
0   56.0  2749.1878733521794    Canoas
1   69.0                 NaN  Gravataí
2  -46.0   5763.566130014205  Gravataí
3   32.0   3911.935197704084    Viamão
4   60.0   5571.251104912366    Viamão

In [ ]:
df['salario'] = pd.to_numeric(df['salario'], errors='coerce')

In [45]:
df['salario'].dtype

dtype('float64')

In [46]:
df.head()

   idade      salario    cidade
0   56.0  2749.187873    Canoas
1   69.0          NaN  Gravataí
2  -46.0  5763.566130  Gravataí
3   32.0  3911.935198    Viamão
4   60.0  5571.251105    Viamão

In [49]:
df["salario"] = df["salario"].astype(float)

In [69]:
df['idade'] = df['idade'].round()

In [68]:
df

    idade      salario        cidade
0    56.0  2749.187873        Canoas
1    69.0          NaN      Gravataí
2   -46.0  5763.566130      Gravataí
3    32.0  3911.935198        Viamão
4    60.0  5571.251105        Viamão
..    ...          ...           ...
95   42.0  5078.778990        Canoas
96   62.0  6403.049176  Porto Alegre
97    NaN  6047.980363        Viamão
98   46.0  5246.780161      Gravataí
99   32.0  3267.819978           NaN

[100 rows x 3 columns]

In [ ]:
df['idade'] = df['idade'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

### 4) Trate os dados nulos: escolha se deve deletar ou substituir os valores nulos.

In [71]:
print(df.dropna())

    idade      salario        cidade
0    56.0  2749.187873        Canoas
2   -46.0  5763.566130      Gravataí
3    32.0  3911.935198        Viamão
4    60.0  5571.251105        Viamão
5    25.0  6564.393522        Canoas
..    ...          ...           ...
93   41.0  5740.404531        Canoas
94   43.0  6498.728839  Porto Alegre
95   42.0  5078.778990        Canoas
96   62.0  6403.049176  Porto Alegre
98   46.0  5246.780161      Gravataí

[71 rows x 3 columns]

In [112]:
df["idade"] = df["idade"].fillna(df["idade"].mean())
df["salario"] = df["salario"].fillna(df["salario"].median())
df['cidade'] = df['cidade'].fillna('não informado')
df.isnull().sum()

idade      0
salario    0
cidade     0
dtype: int64

### 5) Corrija os erros nas variáveis categóricas e transforme todo o texto em minúsculo.

In [73]:
df['cidade'].unique()

<StringArray>
[      'Canoas',     'Gravataí',       'Viamão',        'Cnoas',
 'Porto Alegre',   'Port Algre',       'Viamao',            nan,
      'Viammão',      'Gravatí']
Length: 10, dtype: str

In [ ]:
['Canoas','Gravataí','Viamão','Porto Alegre']
[ 'Cnoas', 'Port Algre','Viamao',nan,'Viammão', 'Gravatí']

In [77]:
erros = df['cidade'].isin(['Cnoas'])
erros

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: cidade, Length: 100, dtype: bool

In [ ]:
cidade_erros = df[ erros]['cidade']
cidade_erros

    idade      salario cidade
6     NaN          NaN  Cnoas
12   41.0  6140.006475  Cnoas
34   33.0  5351.671095  Cnoas
81   48.0  5652.186429  Cnoas

In [114]:
df["cidade"] = df["cidade"].replace({"gravatí": "gravataí"})
df["cidade"] = df["cidade"].replace({"port algre": "porto alegre"})

In [ ]:
df["cidade"] = df["cidade"].replace({"Cnoas": "Canoas"})

In [89]:
df['cidade'].isin(['Cnoas']).sum()

np.int64(0)

In [91]:
df['cidade'] = df['cidade'].replace(['Viamao','Viammão'], 'Viamão')
df['cidade'].isin(['Viamao','Viammão']).sum()

np.int64(0)

In [94]:
df["cidade"] = df["cidade"].str.lower()

### 6) Exclua as linhas duplicadas.

In [93]:
df.drop_duplicates(inplace=True)

### 7) Crie um variável do tipo series com os dados apenas dos usuário de Porto Alegre. Responda:
- a) Qual a média do salário?
- b) Qual a idade média?
- c) Quantos usuários foram encontrados?

In [95]:
usuarioPOA = df[ df['cidade'] == 'porto alegre' ]

In [98]:
usuarioPOA['cidade'].unique()

<StringArray>
['porto alegre']
Length: 1, dtype: str

In [99]:
usuarioPOA['salario'].mean()

np.float64(6239.760343667227)

In [100]:
usuarioPOA['idade'].mean()

np.float64(44.142857142857146)

In [101]:
len(usuarioPOA)

15

### 8) (Extra) Repita a questão 7 para as outras cidades.

In [116]:
lista_cidades = df['cidade'].unique()
lista_cidades

<StringArray>
['canoas', 'gravataí', 'viamão', 'porto alegre', 'não informado']
Length: 5, dtype: str

In [118]:
for i in lista_cidades:
    usuario = df[ df['cidade'] == i ]
    print(f'Média salário de {i} = {usuario['salario'].mean()}')
    print(f'Média de idade de {i} = {usuario['idade'].mean()}')
    print(f'Número de usuários de {i} = {len(usuario)} ')    
    print()

Média salário de canoas = 5718.442698063491
Média de idade de canoas = 38.12177777777778
Número de usuários de canoas = 25

Média salário de gravataí = 4736.86823103204
Média de idade de gravataí = 26.058823529411764
Número de usuários de gravataí = 17

Média salário de viamão = 6116.241968351057
Média de idade de viamão = 40.76797385620915
Número de usuários de viamão = 34

Média salário de porto alegre = 6030.214616013623
Média de idade de porto alegre = 43.25138888888889
Número de usuários de porto alegre = 16

Média salário de não informado = 6032.410027718217
Média de idade de não informado = 41.00555555555556
Número de usuários de não informado = 8