## A metáfora da vez: RPG
Vou tentar (tentar) costurar esse guia com uma grande metáfora de jogo de RPG. Sou jogador de D&D de papel, então vou estar sempre me referindo ao universo da ***Terra Média***, na vibe Senhor dos Anéis, com anões, elfos, guerreiros, paladinos, etc. resolvendo ***missões*** - quests - algumas ***tarefas paralelas*** - side quests - derrotando monstros e salvando princeses, com seu ***equipamentos*** - armaduras, armas - e ***perícias*** - habilidades, poderes.
Mas, vocês podem adaptar para o que desejarem, como jogos de ação, de tiro, universos paranormais, distópicos, etc.

## Organizar o espaço de trabalho (visão geral)
Ao iniciar um novo projeto voltado para a análise de dados, para o treinamento de máquinas (*machine learning*), e para aplicação de modelos estatísticos de IA, é importante se se preparar para essa missão e equipar sua mochila com os recursos necessárias para o sucesso da missão. Mapear o local de origem e destino dos arquivos/fontes/produtos, identificar o tipo, o formato, dos arquivos que serão manipulados e escolher as ferramentas adequadas para o objetivo do projeto são alguns dos exemplos de ações necessárias para iniciar o trabalho.

É evidente que, ao longo da trajetória, surpresas podem surgir e novas soluções terão que ser aplicadas. Talvez, o que se planejou no início, vai se mostrar insuficiente, exigindo que novas pesquisas sejam realizadas, novas ferramentas sejam mobilizadas. Isso não quer dizer que não é necessário se organizar antes. Pelo contrário, quanto melhor se entender o ponto de partida, suas habilidades e suas armas, mais fácil será identificar quando cada um deles deve ser alterado. O mestre sempre tem uma surpresinha, alguns NPCs podem aparecer e demandar tarefas paralelas, ou tu pode acabar descobrindo que ainda tem que upar muito para derrotar o chefão. Ou, quem sabe, formar a guilda certa.

A seguir, vou listar algumas ações iniciais que podem contribuir para a tarefa. Dependendo do projeto, algumas dessas tarefas serão desnecessárias, enquanto outras, que não estão incluídas a baixo, terão que ser aplicadas. 

Se a missão for encontrar um artefato mágico, então os paralelos serão:

### Entender o projeto: a missão
> ***Qual o objetivo deste projeto?***
> Por que é importante encontrar o artefato?
> O que irá determinar que o trabalho está pronto e pode ser finalizado?
> Basta encontrar, ou é preciso quebrar a maldição? 
> Ou, ainda, entregar ele a outra pessoa (uma missão com duas partes?)?
> Será preciso ***entregar um produto final?***
> Esse produto é
	um relatório de análise de dados?
	um modelo de IA?
	um conjunto de dados processados?
	uma API?
	salvar uma aldeia de camponeses inocentes?
> É um ***projeto de pesquisa?***
	Quais são as perguntas de pesquisa?
	Devo propor hipóteses, ou apenas verificar as hipóteses propostas por outros?
	Eu entendo do assunto da pesquisa? 
	Eu preciso entender?

### Dados brutos/originais: o mapa criptografado que nos leva ao artefato
> Como você acessa os dados?
> 	Download, via request http, banco de dados, etc. ?
> ***Qual o formato dos dados?*** É preciso alterar o formato para poder manipular?
> O mapa está em um idioma élfico antigo e será necessário buscar alguém que sabe ler?
> É necessário criar uma cópia deles para manipulação? Onde será registrado?
> Onde serão registradas os dados após seu processamento/correção?
> O mapa está dentro de outro artefato mágico então é preciso realizar a missão de abrir o artefato para ter acesso ao mapa?
> ***Como os dados serão manipulados?***
> Será necessário instalar ou configurar algum software, ou biblioteca para que se possa manipular os dados?

### Ambiente de desenvolvimento: a sala de casa
> Criar um ***ambiente de desenvolvimento*** python para o projeto.
> Configurar o ambiente e a IDE adequados para o projeto.
> Determinar como os scripts, e outros produtos, serão registrados/documentados.
> Ou seja, vamos jogar na tua casa, ou na minha? Quem vai levar a coca e as trakinas?

### Documentação e Caderno de Laboratório: ficha do jogador
> Será necessário versionamento dos códigos?
> O projeto será desenvolvido de maneira individual ou coletiva?
> > Vai ser um jogo de mesa, papel, ou online, digital?
> Como as etapas parciais da pesquisa e desenvolvimento serão registradas? 
> Quais serão as metodologias e softwares ***para registro dee pesquisa e documentação***?
> Vamos anotar em um papel, ou usar as fichas oficiais?

Repare que o ***mapa não é o projeto de pesquisa***. Apesar de ambos mostrarem caminhos que podem ser seguidos, o mapa não tem um objetivo, ele carrega a informação e só. Já o projeto, determina o objetivo final, as quests, os recursos, o ambiente, o universo, a equipe, as limitações, etc. É possível pensar nos dados como nossos inimigos, aqueles que queremos derrotar, manipular, dobrar. Mas não me parece bom, porque eles não são os vilões. Também não são poções mágicas que dão poder e nos possibilitam fazer coisas mágicas, isso quem faz são as ferramentas e recursos que usamos. Eles Podem ser transformados em gráficos e modelos estatísticos, mas permanecem **presentes ao longo de todo o projeto**, são o início e o final. O que queremos descobrir (**inferir!**) já está dentro dele desde o início (**licença poética**). Os caminhos do projeto, ferramentas utilizadas e dificuldades apresentadas são moldadas por ele (**e pelas nossas condições materiais de vida né**). Por isso, entendo que os ***dados informam os trajetos possíveis***, enquanto o ***projeto indica a missão que nossos heróis vão enfrentar***.

Disclaimer: cuidado com a noção de que os dados determinam a realidade, que são inquestionáveis, sendo provas da verdade, nada disso!

## Visão geral dos Dados

### Obter os dados: pegar aquele mapa
(temos que pegar eu sei)

Inicia-se traduzindo o mapa élfico:
>  transformar os dados em algo que poderá ser manipulado com python.

#### Vamos facilitar nosso trabalho e baixar um arquivo do tipo `.csv`.
#### Vamos explorar os dados e depois baixar: [base de dados](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data).

### Ler os dados
Vamos imaginar que de ***élfico antigo*** consigamos traduzir para um idioma chamado ***python***, no dialeto ***pandas***

`pip install pandas`

In [ ]:
import pandas as pd

- [Guia do usuário](https://pandas.pydata.org/docs/user_guide/index.html)

- [Documentação API](https://pandas.pydata.org/docs/reference/)

In [ ]:
df = pd.read_csv("dados\\holidays_events.csv")

In [ ]:
df = pd.read_csv("dados\\holidays_events.csv", sep=',',  na_values=["erro", "$#"])

- Input/output com pandas: [read_tcharara](https://pandas.pydata.org/docs/reference/io.html)

### Conhecer a cara dos dados

É necessário olhar a cara deles. E se vamos colocar em pandas, precisamos que os dados possam ser organizados no formato de ***Dataframes***, ou seja, ***tabelas***.

In [ ]:
df.head()

In [ ]:
df.head(2)

In [ ]:
df.tail(5)

In [ ]:
print(df.size)
print(df.shape)

In [ ]:
df.dtypes

In [ ]:
df.info()

Verificar o nome das colunas, quem é o index (linhas).

In [ ]:
print(df.columns)

In [ ]:
print(df.index)

##### Muitas outras formas de acessar e olhar para esses caras
-> [Dataframes](https://pandas.pydata.org/docs/reference/frame.html)

### Atividade
##### Baixo os os dados, disponíveis [aqui](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data), e responda as seguintes questões (15min):

> 1. Qual o separador dos dados?

Vírgula

> 2. Quantas colunas a base de dados tem?

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
len(df.columns)


> 3. Qual a diferença entre o número de linhas e o index?

- Linhas e index são equivalentes!
- Linhas são as linhas da tabela.
- Cada index é um índice que identificam uma linha.
- Os index estão listados em uma coluna chamada 'index'.
- O index é o nome da linha, tal qual columns é o nome das colunas.

In [ ]:
df.shape

In [ ]:
len(df.index)

In [ ]:
list(df.index)

In [ ]:
df.head(10)


> 4. Qual o tipo de dados de cada coluna? Que problemas você antecipa?

In [ ]:
df.dtypes

In [ ]:
df.head()


> 5. Por que alguns comandos tem `()` e outros não? Por exemplo, `df.dtypes` e `df.info()`.

- Com () são métodos, são funções, são ações;
- Sem () são propriedades, características.

Por exemplo, a carteira de motorista é uma propriedade, mas dirigir é uma ação.

In [ ]:
df.info()

In [ ]:
df.info

> 6. Qual a diferença entre `print(df.size())` e `df.size`?

### ERREI! `df.size()` É UMA PROPRIEDADE, NÃO UM MÉTODO, NÃO TEM '()'!

In [ ]:
df.size()

In [ ]:
df.size

##### O que eu queria perguntar é a diferença entre `print(df.size)` e `df.size`

In [ ]:
print(df.size)
df.size

In [ ]:
df.size
print(df.size)

In [ ]:
df.size

### Não há diferenças! São equivalentes.
- `df.size` apenas executa o comando
- `print(df.size)` executa e imprime

No jupyter, o resultado do último comando de cada célula é impresso, por isso conseguimos ver o resultado apenas digitando `df.size`.

## Acessar itens: passo de exploração
##### Esse trecho não é um passo necessário, mas acho interessante mostrar como fazer isso.

In [ ]:
df.columns

In [ ]:
df['locale']

In [ ]:
df[ ['locale', 'type']  ]

#### Filtrar

Acessar valores que satisfazem uma condição.

In [ ]:
df[df["transferred"] != False] # valores que satisfazem a condição, independente de coluna/linha

In [ ]:
df["transferred"] != False

In [67]:
lista = df["transferred"] != False

In [68]:
df[lista]

,date,type,locale,locale_name,description,transferred
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
72,2013-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
135,2014-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
255,2016-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
266,2016-07-25,Holiday,Local,Guayaquil,Fundacion de Guayaquil,True
268,2016-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
297,2017-01-01,Holiday,National,Ecuador,Primer dia del ano,True
303,2017-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,True
312,2017-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
324,2017-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
328,2017-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,True
340,2017-12-06,Holiday,Local,Quito,Fundacion de Quito,True

In [ ]:
df[df["transferred"] != False]['type']

In [69]:
df[ df['locale'] == 'National' ]

,date,type,locale,locale_name,description,transferred
14,2012-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,False
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
20,2012-10-12,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
21,2012-11-02,Holiday,National,Ecuador,Dia de Difuntos,False
22,2012-11-03,Holiday,National,Ecuador,Independencia de Cuenca,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

##### Filtrar itens que estão em uma lista

In [71]:
favoritos = ['Imbabura','Latacunga','Machala','Santo Domingo','El Carmen','Cayambe','Esmerald']

In [72]:
df.isin(favoritos) # condição de pertencimento

      date   type  locale  locale_name  description  transferred
0    False  False   False        False        False        False
1    False  False   False        False        False        False
2    False  False   False        False        False        False
3    False  False   False        False        False        False
4    False  False   False        False        False        False
..     ...    ...     ...          ...          ...          ...
345  False  False   False        False        False        False
346  False  False   False        False        False        False
347  False  False   False        False        False        False
348  False  False   False        False        False        False
349  False  False   False        False        False        False

[350 rows x 6 columns]

In [73]:
df['type'].isin(favoritos)

0      False
1      False
2      False
3      False
4      False
       ...
345    False
346    False
347    False
348    False
349    False
Name: type, Length: 350, dtype: bool

In [74]:
df.isin(favoritos).sum()

date            0
type            0
locale          0
locale_name    42
description     0
transferred     0
dtype: int64

In [75]:
df[df['locale_name'].isin(favoritos)]

,date,type,locale,locale_name,description,transferred
7,2012-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
8,2012-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
9,2012-06-25,Holiday,Local,Machala,Fundacion de Machala,False
10,2012-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
11,2012-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
12,2012-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
26,2012-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
58,2013-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
59,2013-06-25,Holiday,Local,Machala,Fundacion de Machala,False
60,2013-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
61,2013-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
62,2013-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
63,2013-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
79,2013-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
110,2014-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
111,2014-06-25,Holiday,Local,Machala,Fundacion de Machala,False
112,2014-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
118,2014-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
119,2014-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
126,2014-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
142,2014-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
176,2015-06-25,Holiday,Local,Machala,Fundacion de Machala,False
177,2015-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
178,2015-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
179,2015-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
180,2015-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
181,2015-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
196,2015-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
258,2016-06-25,Holiday,Local,Machala,Fundacion de Machala,False
259,2016-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
260,2016-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
261,2016-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
262,2016-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
263,2016-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
281,2016-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
315,2017-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
316,2017-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
317,2017-06-25,Holiday,Local,Machala,Fundacion de Machala,False
318,2017-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
319,2017-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
320,2017-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
337,2017-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False

In [76]:
df[df['locale_name'].isin(favoritos)]['locale_name']

7           Imbabura
8          Latacunga
9            Machala
10     Santo Domingo
11         El Carmen
12           Cayambe
26         Latacunga
58          Imbabura
59           Machala
60         Latacunga
61         El Carmen
62     Santo Domingo
63           Cayambe
79         Latacunga
110        Latacunga
111          Machala
112         Imbabura
118        El Carmen
119    Santo Domingo
126          Cayambe
142        Latacunga
176          Machala
177         Imbabura
178        Latacunga
179        El Carmen
180    Santo Domingo
181          Cayambe
196        Latacunga
258          Machala
259         Imbabura
260        Latacunga
261        El Carmen
262    Santo Domingo
263          Cayambe
281        Latacunga
315         Imbabura
316        Latacunga
317          Machala
318        El Carmen
319    Santo Domingo
320          Cayambe
337        Latacunga
Name: locale_name, dtype: str

#### Identificar categorias, espectro, intervalo

In [78]:
df['locale'].unique()

<StringArray>
['Local', 'Regional', 'National']
Length: 3, dtype: str

#### Acessar itens pela posição

- [Indexing](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-basics-get-value)

In [79]:
df.iloc[0] # Posição numérica / index / linha

date                   2012-03-02
type                      Holiday
locale                      Local
locale_name                 Manta
description    Fundacion de Manta
transferred                 False
Name: 0, dtype: object

In [ ]:
df.iloc[[0,1]]

In [80]:
df.loc[[0,1]]# Posição segundo o NOME DO ÍNDICE

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False

> ##### São o mesmo resultado por que NESTE CASOS dos índex são iguais a sua posição.

> ####  Hmmm -> Por que está sendo usado `[]` e não `()`?  -.^

In [84]:
df.iloc[4]

date                          2012-04-21
type                             Holiday
locale                             Local
locale_name                     Riobamba
description    Cantonizacion de Riobamba
transferred                        False
Name: 4, dtype: object

In [86]:
df.head(5)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [88]:
df['type'][0]

'Holiday'

In [89]:
df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [90]:
df.columns[2]

'locale'

In [91]:
df['date']

0      2012-03-02
1      2012-04-01
2      2012-04-12
3      2012-04-14
4      2012-04-21
          ...
345    2017-12-22
346    2017-12-23
347    2017-12-24
348    2017-12-25
349    2017-12-26
Name: date, Length: 350, dtype: str

In [92]:
df['date'][2]

'2012-04-12'


#### Series em pandas

##### Dataframe é um conjunto de colunas.
##### Uma coluna sozinha é uma série.

In [93]:
serie1 = df['type']
print(serie1)

0         Holiday
1         Holiday
2         Holiday
3         Holiday
4         Holiday
          ...
345    Additional
346    Additional
347    Additional
348       Holiday
349    Additional
Name: type, Length: 350, dtype: str

##### Alguns métodos de pandas podem ser aplicados apenas a séries, alguns métodos apenas em dataframes.
- [`Series.str.startswith`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.startswith.html#pandas.Series.str.startswith "pandas.Series.str.startswith")
- [`Series.str.endswith`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.endswith.html#pandas.Series.str.endswith "pandas.Series.str.endswith")
- [`Series.str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains "pandas.Series.str.contains")

In [94]:
df.eq(serie1, axis='index') # condição de equivalência entre df e series

      date  type  locale  locale_name  description  transferred
0    False  True   False        False        False        False
1    False  True   False        False        False        False
2    False  True   False        False        False        False
3    False  True   False        False        False        False
4    False  True   False        False        False        False
..     ...   ...     ...          ...          ...          ...
345  False  True   False        False        False        False
346  False  True   False        False        False        False
347  False  True   False        False        False        False
348  False  True   False        False        False        False
349  False  True   False        False        False        False

[350 rows x 6 columns]

In [95]:
serie2 = df.iloc[3]
print(serie2)

date                          2012-04-14
type                             Holiday
locale                             Local
locale_name                     Libertad
description    Cantonizacion de Libertad
transferred                        False
Name: 3, dtype: object

In [96]:
df.eq(serie2, axis='columns')

      date   type  locale  locale_name  description  transferred
0    False   True    True        False        False         True
1    False   True   False        False        False         True
2    False   True    True        False        False         True
3     True   True    True         True         True         True
4    False   True    True        False        False         True
..     ...    ...     ...          ...          ...          ...
345  False  False   False        False        False         True
346  False  False   False        False        False         True
347  False  False   False        False        False         True
348  False   True   False        False        False         True
349  False  False   False        False        False         True

[350 rows x 6 columns]

In [97]:
df[df.eq(serie2, axis='columns')] # equivalente à df[df.eq(serie2, axis='columns') == True]

,date,type,locale,locale_name,description,transferred
0,NaN,Holiday,Local,NaN,NaN,False
1,NaN,Holiday,NaN,NaN,NaN,False
2,NaN,Holiday,Local,NaN,NaN,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,NaN,Holiday,Local,NaN,NaN,False
...,...,...,...,...,...,...
345,NaN,NaN,NaN,NaN,NaN,False
346,NaN,NaN,NaN,NaN,NaN,False
347,NaN,NaN,NaN,NaN,NaN,False
348,NaN,Holiday,NaN,NaN,NaN,False
349,NaN,NaN,NaN,NaN,NaN,False

#### Voltando para o roteiro, vamos iniciar outra etapa:
## Limpeza dos dados

Nesta etapa, vamos limpar os dados: corrigir tipos, tratar nulos e faltantes, incorretos, outliers e etc.

## Limpeza dos dados: Corrigir tipos

In [ ]:
df.dtypes

In [ ]:
df.head(2)

In [ ]:
date_series = pd.to_datetime(['2012-03-02', '2012-04-01', '2012-04-12', '2012-04-14', '2012-04-2'])
print(date_series)

In [ ]:
df['date'] = pd.to_datetime( df['date'] )
print(df.info())

In [ ]:
exemplo = pd.DataFrame(['1', '3', '5', '8'])
exemplo.dtypes

In [ ]:
exemplo = pd.to_numeric(exemplo[0])
exemplo.dtypes

- [Mais sobre converter string para datetime.](https://www.datacamp.com/tutorial/converting-strings-datetime-objects)
- [Para quem quer entender sobre o que são tipos de dados em python e quais são eles.](https://www.datacamp.com/blog/python-data-types)
- [Lista com tipos de dados.](https://pandas.pydata.org/docs/reference/arrays.html)
- Converter para numérico: [pd.to_numeric()](https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#)

## Limpeza dos dados: Identificar nulos e faltantes

Valores marcados como NA, None, Vazio, etc. Eles irão prejudicar a análise e precisam ser corrigidos.

As estratégias para resolver esse problema podem ser resumidas em: ***deletar*** ou ***substituir***.

|Ação | Prós| Contras | Algorítimo|
|---|---|---|---|
| Deletar todas as linhas com pelo menos 1 valor nulo | Fácil, rápido, não altera o comportamento da amostra| Para bases pequenas, ou para muitos valores nulos, deletar pode prejudicar o tamanho da amostra, e leva a perda de valores não nulos.| Filtrar e deletar: `df.dropna()`|
| Substituir pela média/moda| Não há perda de dados, não altera o comportamento médio| Altera o comportamento local, pode afetar a análise| Filtrar e substituir pela média/moda da coluna: `df.fillna()` e `df.mean()`. Para dados categóricos, usar o valor mais frequente.|
| Substituir por uma nova categoria "Não informado", ou 0 | Não há perda de dados | Pode alterar o comportamento médio e local, adiciona mais uma categoria para análise| Filtrar e substituir: `df.fillna()`e `= "Não informado"`| 
|Deletar a coluna: quando há uma coluna com muitos valores nulos, pode ser vantajoso excluir ela da análise| Fácil, não interfere no comportamento geral | Se a variável for relevante para a análise, pode prejudicar o resultado| Deletar: `df.drop()`|

#### Verificando na nossa base:

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

#### Mas se tivesse nulo, o que poderiamos fazer?

Vou inserir dados nulos falsos

In [ ]:
df.iloc[1] = [None, None,None,None, None, None]

In [ ]:
print(df.head(3))

In [ ]:
print(df.info())
print(df.isnull().sum())

In [ ]:
df.dropna(axis='index', inplace=True)
# df = df.dropna(axis='index')
print(df.values)

##### Observação: clicando na função com ctrl ou botão direito -> ver implementação

### Limpeza dos dados: linhas repetidas

In [ ]:
df.duplicated()

In [ ]:
df.duplicated().sum()

> - Para deletar as duplicatas: [df.drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html)

### Limpeza dos dados: erros de escrita

In [ ]:
df.unique() # vai dar erro

In [ ]:
df.columns

In [ ]:
print(df['type'].unique())
print(df['locale'].unique())
print(df['locale_name'].unique())
print(df['description'].unique())

##### Parece que não tem nenhum erro . . .mas e se quiséssemos que tudo estivesse com letra minúscula?

In [ ]:
df['type'].str.lower()

##### E para fazer para todos os campos?

In [ ]:
# df.columns
campos_categoricos = ['type', 'locale', 'locale_name', 'description']
for campo in campos_categoricos:
    print(campo)
    df[campo] = df[campo].str.lower()
    print(df[campo].unique())
    print('')

#### Caso queira corrigir palavras ou alterar nomes:

In [ ]:
df.replace('holiday', 'férias', inplace=True)
print(df['type'].unique())

### Limpeza de dados: Outliers

Outliers são dados que fogem a norma. Dados que são tão diferentes que podem prejudicar a análise.
Vamos entender eles mais tarde, depois de aprendermos a fazer análise visual e estatística descritiva.

## Atividade

### Tratamento dos dados\atividade_02.ipynb

### Atividades Extras 
1. Substitua todas as palavras em inglês no campo 'type' por suas traduções para o português. Use um loop para agilizr a substituição

```
ingles = ['holiday', 'transfer', 'additional', 'bridge', 'work day', 'event']`
traducao = ['férias', 'transferência', 'adicional', 'ponte', 'dia útil', 'evento']
```

2. Substitua todos os valores booleanos do campo 'transfered' for 0 e 1, para `False` e `True`, respectivamente.

# Próximos passos: Estatística Descritiva, Análise Visual e Identificação de Outliers

# Estatística descritiva

In [102]:
df.describe()

              date     type    locale locale_name description transferred
count          350      350       350         350         350         350
unique         312        6         3          24         103           2
top     2014-06-25  Holiday  National     Ecuador    Carnaval       False
freq             4      221       174         174          10         338

Vamos adicionar uma coluna fictícia com preços