## A metáfora da vez: RPG
Vou tentar (tentar) costurar esse guia com uma grande metáfora de jogo de RPG. Sou jogador de D&D de papel, então vou estar sempre me referindo ao universo da ***Terra Média***, na vibe Senhor dos Anéis, com anões, elfos, guerreiros, paladinos, etc. resolvendo ***missões*** - quests - algumas ***tarefas paralelas*** - side quests - derrotando monstros e salvando princeses, com seu ***equipamentos*** - armaduras, armas - e ***perícias*** - habilidades, poderes.
Mas, vocês podem adaptar para o que desejarem, como jogos de ação, de tiro, universos paranormais, distópicos, etc.

## Organizar o espaço de trabalho (visão geral)
Ao iniciar um novo projeto voltado para a análise de dados, para o treinamento de máquinas (*machine learning*), e para aplicação de modelos estatísticos de IA, é importante se se preparar para essa missão e equipar sua mochila com os recursos necessárias para o sucesso da missão. Mapear o local de origem e destino dos arquivos/fontes/produtos, identificar o tipo, o formato, dos arquivos que serão manipulados e escolher as ferramentas adequadas para o objetivo do projeto são alguns dos exemplos de ações necessárias para iniciar o trabalho.

É evidente que, ao longo da trajetória, surpresas podem surgir e novas soluções terão que ser aplicadas. Talvez, o que se planejou no início, vai se mostrar insuficiente, exigindo que novas pesquisas sejam realizadas, novas ferramentas sejam mobilizadas. Isso não quer dizer que não é necessário se organizar antes. Pelo contrário, quanto melhor se entender o ponto de partida, suas habilidades e suas armas, mais fácil será identificar quando cada um deles deve ser alterado. O mestre sempre tem uma surpresinha, alguns NPCs podem aparecer e demandar tarefas paralelas, ou tu pode acabar descobrindo que ainda tem que upar muito para derrotar o chefão. Ou, quem sabe, formar a guilda certa.

A seguir, vou listar algumas ações iniciais que podem contribuir para a tarefa. Dependendo do projeto, algumas dessas tarefas serão desnecessárias, enquanto outras, que não estão incluídas a baixo, terão que ser aplicadas. 

Se a missão for encontrar um artefato mágico, então os paralelos serão:

### Entender o projeto: a missão
> ***Qual o objetivo deste projeto?***
> Por que é importante encontrar o artefato?
> O que irá determinar que o trabalho está pronto e pode ser finalizado?
> Basta encontrar, ou é preciso quebrar a maldição? 
> Ou, ainda, entregar ele a outra pessoa (uma missão com duas partes?)?
> Será preciso ***entregar um produto final?***
> Esse produto é
	um relatório de análise de dados?
	um modelo de IA?
	um conjunto de dados processados?
	uma API?
	salvar uma aldeia de camponeses inocentes?
> É um ***projeto de pesquisa?***
	Quais são as perguntas de pesquisa?
	Devo propor hipóteses, ou apenas verificar as hipóteses propostas por outros?
	Eu entendo do assunto da pesquisa? 
	Eu preciso entender?

### Dados brutos/originais: o mapa criptografado que nos leva ao artefato
> Como você acessa os dados?
> 	Download, via request http, banco de dados, etc. ?
> ***Qual o formato dos dados?*** É preciso alterar o formato para poder manipular?
> O mapa está em um idioma élfico antigo e será necessário buscar alguém que sabe ler?
> É necessário criar uma cópia deles para manipulação? Onde será registrado?
> Onde serão registradas os dados após seu processamento/correção?
> O mapa está dentro de outro artefato mágico então é preciso realizar a missão de abrir o artefato para ter acesso ao mapa?
> ***Como os dados serão manipulados?***
> Será necessário instalar ou configurar algum software, ou biblioteca para que se possa manipular os dados?

### Ambiente de desenvolvimento: a sala de casa
> Criar um ***ambiente de desenvolvimento*** python para o projeto.
> Configurar o ambiente e a IDE adequados para o projeto.
> Determinar como os scripts, e outros produtos, serão registrados/documentados.
> Ou seja, vamos jogar na tua casa, ou na minha? Quem vai levar a coca e as trakinas?

### Documentação e Caderno de Laboratório: ficha do jogador
> Será necessário versionamento dos códigos?
> O projeto será desenvolvido de maneira individual ou coletiva?
> > Vai ser um jogo de mesa, papel, ou online, digital?
> Como as etapas parciais da pesquisa e desenvolvimento serão registradas? 
> Quais serão as metodologias e softwares ***para registro dee pesquisa e documentação***?
> Vamos anotar em um papel, ou usar as fichas oficiais?

Repare que o ***mapa não é o projeto de pesquisa***. Apesar de ambos mostrarem caminhos que podem ser seguidos, o mapa não tem um objetivo, ele carrega a informação e só. Já o projeto, determina o objetivo final, as quests, os recursos, o ambiente, o universo, a equipe, as limitações, etc. É possível pensar nos dados como nossos inimigos, aqueles que queremos derrotar, manipular, dobrar. Mas não me parece bom, porque eles não são os vilões. Também não são poções mágicas que dão poder e nos possibilitam fazer coisas mágicas, isso quem faz são as ferramentas e recursos que usamos. Eles Podem ser transformados em gráficos e modelos estatísticos, mas permanecem **presentes ao longo de todo o projeto**, são o início e o final. O que queremos descobrir (**inferir!**) já está dentro dele desde o início (**licença poética**). Os caminhos do projeto, ferramentas utilizadas e dificuldades apresentadas são moldadas por ele (**e pelas nossas condições materiais de vida né**). Por isso, entendo que os ***dados informam os trajetos possíveis***, enquanto o ***projeto indica a missão que nossos heróis vão enfrentar***.

Disclaimer: cuidado com a noção de que os dados determinam a realidade, que são inquestionáveis, sendo provas da verdade, nada disso!

## Visão geral dos Dados

### Obter os dados: pegar aquele mapa
(temos que pegar eu sei)

Inicia-se traduzindo o mapa élfico:
>  transformar os dados em algo que poderá ser manipulado com python.

#### Vamos facilitar nosso trabalho e baixar um arquivo do tipo `.csv`.
#### Vamos explorar os dados e depois baixar: [base de dados](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data).

### Ler os dados
Vamos imaginar que de ***élfico antigo*** consigamos traduzir para um idioma chamado ***python***, no dialeto ***pandas***

`pip install pandas`

In [80]:
import pandas as pd

- [Guia do usuário](https://pandas.pydata.org/docs/user_guide/index.html)

- [Documentação API](https://pandas.pydata.org/docs/reference/)

In [81]:
df = pd.read_csv("dados\\holidays_events.csv")

In [82]:
df = pd.read_csv("dados\\holidays_events.csv", sep=',',  na_values=["erro", "$#"])

- Input/output com pandas: [read_tcharara](https://pandas.pydata.org/docs/reference/io.html)

### Conhecer a cara dos dados

É necessário olhar a cara deles. E se vamos colocar em pandas, precisamos que os dados possam ser organizados no formato de ***Dataframes***, ou seja, ***tabelas***.

In [83]:
df.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [84]:
df.head(2)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False

In [85]:
df.tail(5)

           date        type    locale locale_name description  transferred
345  2017-12-22  Additional  National     Ecuador   Navidad-3        False
346  2017-12-23  Additional  National     Ecuador   Navidad-2        False
347  2017-12-24  Additional  National     Ecuador   Navidad-1        False
348  2017-12-25     Holiday  National     Ecuador     Navidad        False
349  2017-12-26  Additional  National     Ecuador   Navidad+1        False

In [86]:
print(df.size)
print(df.shape)

2100
(350, 6)

In [87]:
df.dtypes

date            str
type            str
locale          str
locale_name     str
description     str
transferred    bool
dtype: object

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    str
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), str(5)
memory usage: 14.1 KB

Verificar o nome das colunas, quem é o index (linhas).

In [89]:
print(df.columns)

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [90]:
print(df.index)

RangeIndex(start=0, stop=350, step=1)

##### Muitas outras formas de acessar e olhar para esses caras
-> [Dataframes](https://pandas.pydata.org/docs/reference/frame.html)

### Atividade
##### Baixo os os dados, disponíveis [aqui](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data), e responda as seguintes questões (15min):

> 1. Qual o separador dos dados?

Vírgula

> 2. Quantas colunas a base de dados tem?

In [91]:
df.shape

(350, 6)

In [92]:
df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [93]:
len(df.columns)

6


> 3. Qual a diferença entre o número de linhas e o index?

- Linhas e index são equivalentes!
- Linhas são as linhas da tabela.
- Cada index é um índice que identificam uma linha.
- Os index estão listados em uma coluna chamada 'index'.
- O index é o nome da linha, tal qual columns é o nome das colunas.

In [94]:
df.shape

(350, 6)

In [95]:
len(df.index)

350

In [96]:
list(df.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349]

In [97]:
df.head(10)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
5,2012-05-12,Holiday,Local,Puyo,Cantonizacion del Puyo,False
6,2012-06-23,Holiday,Local,Guaranda,Cantonizacion de Guaranda,False
7,2012-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
8,2012-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
9,2012-06-25,Holiday,Local,Machala,Fundacion de Machala,False


> 4. Qual o tipo de dados de cada coluna? Que problemas você antecipa?

In [98]:
df.dtypes

date            str
type            str
locale          str
locale_name     str
description     str
transferred    bool
dtype: object

In [99]:
df.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False


> 5. Por que alguns comandos tem `()` e outros não? Por exemplo, `df.dtypes` e `df.info()`.

- Com () são métodos, são funções, são ações;
- Sem () são propriedades, características.

Por exemplo, a carteira de motorista é uma propriedade, mas dirigir é uma ação.

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    str
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), str(5)
memory usage: 14.1 KB

In [101]:
df.info

<bound method DataFrame.info of            date        type    locale locale_name  \
0    2012-03-02     Holiday     Local       Manta
1    2012-04-01     Holiday  Regional    Cotopaxi
2    2012-04-12     Holiday     Local      Cuenca
3    2012-04-14     Holiday     Local    Libertad
4    2012-04-21     Holiday     Local    Riobamba
..          ...         ...       ...         ...
345  2017-12-22  Additional  National     Ecuador
346  2017-12-23  Additional  National     Ecuador
347  2017-12-24  Additional  National     Ecuador
348  2017-12-25     Holiday  National     Ecuador
349  2017-12-26  Additional  National     Ecuador

                       description  transferred
0               Fundacion de Manta        False
1    Provincializacion de Cotopaxi        False
2              Fundacion de Cuenca        False
3        Cantonizacion de Libertad        False
4        Cantonizacion de Riobamba        False
..                             ...          ...
345                      Navidad-3        False
346                      Navidad-2        False
347                      Navidad-1        False
348                        Navidad        False
349                      Navidad+1        False

[350 rows x 6 columns]>

> 6. Qual a diferença entre `print(df.size())` e `df.size`?

### ERREI! `df.size()` É UMA PROPRIEDADE, NÃO UM MÉTODO, NÃO TEM '()'!

In [102]:
#df.size()

In [103]:
df.size

2100

##### O que eu queria perguntar é a diferença entre `print(df.size)` e `df.size`

In [104]:
print(df.size)
df.size

2100

2100

In [105]:
df.size
print(df.size)

2100

In [106]:
df.size

2100

### Não há diferenças! São equivalentes.
- `df.size` apenas executa o comando
- `print(df.size)` executa e imprime

No jupyter, o resultado do último comando de cada célula é impresso, por isso conseguimos ver o resultado apenas digitando `df.size`.

## Acessar itens: passo de exploração
##### Esse trecho não é um passo necessário, mas acho interessante mostrar como fazer isso.

In [107]:
df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [108]:
df['locale']

0         Local
1      Regional
2         Local
3         Local
4         Local
         ...
345    National
346    National
347    National
348    National
349    National
Name: locale, Length: 350, dtype: str

In [109]:
df[ ['locale', 'type']  ]

       locale        type
0       Local     Holiday
1    Regional     Holiday
2       Local     Holiday
3       Local     Holiday
4       Local     Holiday
..        ...         ...
345  National  Additional
346  National  Additional
347  National  Additional
348  National     Holiday
349  National  Additional

[350 rows x 2 columns]

#### Filtrar

Acessar valores que satisfazem uma condição.

In [110]:
df[df["transferred"] != False] # valores que satisfazem a condição, independente de coluna/linha

,date,type,locale,locale_name,description,transferred
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
72,2013-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
135,2014-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
255,2016-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
266,2016-07-25,Holiday,Local,Guayaquil,Fundacion de Guayaquil,True
268,2016-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
297,2017-01-01,Holiday,National,Ecuador,Primer dia del ano,True
303,2017-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,True
312,2017-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
324,2017-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
328,2017-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,True
340,2017-12-06,Holiday,Local,Quito,Fundacion de Quito,True

In [111]:
df["transferred"] != False

0      False
1      False
2      False
3      False
4      False
       ...
345    False
346    False
347    False
348    False
349    False
Name: transferred, Length: 350, dtype: bool

In [112]:
lista = df["transferred"] != False

In [113]:
df[lista]

,date,type,locale,locale_name,description,transferred
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
72,2013-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
135,2014-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
255,2016-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
266,2016-07-25,Holiday,Local,Guayaquil,Fundacion de Guayaquil,True
268,2016-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
297,2017-01-01,Holiday,National,Ecuador,Primer dia del ano,True
303,2017-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,True
312,2017-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
324,2017-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
328,2017-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,True
340,2017-12-06,Holiday,Local,Quito,Fundacion de Quito,True

In [114]:
df[df["transferred"] != False]['type']

19     Holiday
72     Holiday
135    Holiday
255    Holiday
266    Holiday
268    Holiday
297    Holiday
303    Holiday
312    Holiday
324    Holiday
328    Holiday
340    Holiday
Name: type, dtype: str

In [115]:
df[ df['locale'] == 'National' ]

,date,type,locale,locale_name,description,transferred
14,2012-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,False
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
20,2012-10-12,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
21,2012-11-02,Holiday,National,Ecuador,Dia de Difuntos,False
22,2012-11-03,Holiday,National,Ecuador,Independencia de Cuenca,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

##### Filtrar itens que estão em uma lista

In [116]:
favoritos = ['Imbabura','Latacunga','Machala','Santo Domingo','El Carmen','Cayambe','Esmerald']

In [117]:
df.isin(favoritos) # condição de pertencimento

      date   type  locale  locale_name  description  transferred
0    False  False   False        False        False        False
1    False  False   False        False        False        False
2    False  False   False        False        False        False
3    False  False   False        False        False        False
4    False  False   False        False        False        False
..     ...    ...     ...          ...          ...          ...
345  False  False   False        False        False        False
346  False  False   False        False        False        False
347  False  False   False        False        False        False
348  False  False   False        False        False        False
349  False  False   False        False        False        False

[350 rows x 6 columns]

In [118]:
df['type'].isin(favoritos)

0      False
1      False
2      False
3      False
4      False
       ...
345    False
346    False
347    False
348    False
349    False
Name: type, Length: 350, dtype: bool

In [119]:
df.isin(favoritos).sum()

date            0
type            0
locale          0
locale_name    42
description     0
transferred     0
dtype: int64

In [120]:
df[df['locale_name'].isin(favoritos)]

,date,type,locale,locale_name,description,transferred
7,2012-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
8,2012-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
9,2012-06-25,Holiday,Local,Machala,Fundacion de Machala,False
10,2012-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
11,2012-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
12,2012-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
26,2012-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
58,2013-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
59,2013-06-25,Holiday,Local,Machala,Fundacion de Machala,False
60,2013-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
61,2013-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
62,2013-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
63,2013-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
79,2013-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
110,2014-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
111,2014-06-25,Holiday,Local,Machala,Fundacion de Machala,False
112,2014-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
118,2014-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
119,2014-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
126,2014-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
142,2014-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
176,2015-06-25,Holiday,Local,Machala,Fundacion de Machala,False
177,2015-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
178,2015-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
179,2015-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
180,2015-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
181,2015-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
196,2015-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
258,2016-06-25,Holiday,Local,Machala,Fundacion de Machala,False
259,2016-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
260,2016-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
261,2016-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
262,2016-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
263,2016-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
281,2016-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False
315,2017-06-25,Holiday,Regional,Imbabura,Provincializacion de Imbabura,False
316,2017-06-25,Holiday,Local,Latacunga,Cantonizacion de Latacunga,False
317,2017-06-25,Holiday,Local,Machala,Fundacion de Machala,False
318,2017-07-03,Holiday,Local,El Carmen,Cantonizacion de El Carmen,False
319,2017-07-03,Holiday,Local,Santo Domingo,Fundacion de Santo Domingo,False
320,2017-07-23,Holiday,Local,Cayambe,Cantonizacion de Cayambe,False
337,2017-11-11,Holiday,Local,Latacunga,Independencia de Latacunga,False

In [121]:
df[df['locale_name'].isin(favoritos)]['locale_name']

7           Imbabura
8          Latacunga
9            Machala
10     Santo Domingo
11         El Carmen
12           Cayambe
26         Latacunga
58          Imbabura
59           Machala
60         Latacunga
61         El Carmen
62     Santo Domingo
63           Cayambe
79         Latacunga
110        Latacunga
111          Machala
112         Imbabura
118        El Carmen
119    Santo Domingo
126          Cayambe
142        Latacunga
176          Machala
177         Imbabura
178        Latacunga
179        El Carmen
180    Santo Domingo
181          Cayambe
196        Latacunga
258          Machala
259         Imbabura
260        Latacunga
261        El Carmen
262    Santo Domingo
263          Cayambe
281        Latacunga
315         Imbabura
316        Latacunga
317          Machala
318        El Carmen
319    Santo Domingo
320          Cayambe
337        Latacunga
Name: locale_name, dtype: str

#### Identificar categorias, espectro, intervalo

In [122]:
df['locale'].unique()

<StringArray>
['Local', 'Regional', 'National']
Length: 3, dtype: str

#### Acessar itens pela posição

- [Indexing](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-basics-get-value)

In [123]:
df.iloc[0] # Posição numérica / index / linha

date                   2012-03-02
type                      Holiday
locale                      Local
locale_name                 Manta
description    Fundacion de Manta
transferred                 False
Name: 0, dtype: object

In [124]:
df.iloc[[0,1]]

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False

In [125]:
df.loc[[0,1]]# Posição segundo o NOME DO ÍNDICE

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False

> ##### São o mesmo resultado por que NESTE CASOS dos índex são iguais a sua posição.

> ####  Hmmm -> Por que está sendo usado `[]` e não `()`?  -.^

In [126]:
df.iloc[4]

date                          2012-04-21
type                             Holiday
locale                             Local
locale_name                     Riobamba
description    Cantonizacion de Riobamba
transferred                        False
Name: 4, dtype: object

In [127]:
df.head(5)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [128]:
df['type'][0]

'Holiday'

In [129]:
df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [130]:
df.columns[2]

'locale'

In [131]:
df['date']

0      2012-03-02
1      2012-04-01
2      2012-04-12
3      2012-04-14
4      2012-04-21
          ...
345    2017-12-22
346    2017-12-23
347    2017-12-24
348    2017-12-25
349    2017-12-26
Name: date, Length: 350, dtype: str

In [132]:
df['date'][2]

'2012-04-12'


#### Series em pandas

##### Dataframe é um conjunto de colunas.
##### Uma coluna sozinha é uma série.

In [133]:
serie1 = df['type']
print(serie1)

0         Holiday
1         Holiday
2         Holiday
3         Holiday
4         Holiday
          ...
345    Additional
346    Additional
347    Additional
348       Holiday
349    Additional
Name: type, Length: 350, dtype: str

##### Alguns métodos de pandas podem ser aplicados apenas a séries, alguns métodos apenas em dataframes.
- [`Series.str.startswith`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.startswith.html#pandas.Series.str.startswith "pandas.Series.str.startswith")
- [`Series.str.endswith`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.endswith.html#pandas.Series.str.endswith "pandas.Series.str.endswith")
- [`Series.str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains "pandas.Series.str.contains")

In [134]:
df.eq(serie1, axis='index') # condição de equivalência entre df e series

      date  type  locale  locale_name  description  transferred
0    False  True   False        False        False        False
1    False  True   False        False        False        False
2    False  True   False        False        False        False
3    False  True   False        False        False        False
4    False  True   False        False        False        False
..     ...   ...     ...          ...          ...          ...
345  False  True   False        False        False        False
346  False  True   False        False        False        False
347  False  True   False        False        False        False
348  False  True   False        False        False        False
349  False  True   False        False        False        False

[350 rows x 6 columns]

In [135]:
serie2 = df.iloc[3]
print(serie2)

date                          2012-04-14
type                             Holiday
locale                             Local
locale_name                     Libertad
description    Cantonizacion de Libertad
transferred                        False
Name: 3, dtype: object

In [136]:
df.eq(serie2, axis='columns')

      date   type  locale  locale_name  description  transferred
0    False   True    True        False        False         True
1    False   True   False        False        False         True
2    False   True    True        False        False         True
3     True   True    True         True         True         True
4    False   True    True        False        False         True
..     ...    ...     ...          ...          ...          ...
345  False  False   False        False        False         True
346  False  False   False        False        False         True
347  False  False   False        False        False         True
348  False   True   False        False        False         True
349  False  False   False        False        False         True

[350 rows x 6 columns]

In [137]:
df[df.eq(serie2, axis='columns')] # equivalente à df[df.eq(serie2, axis='columns') == True]

,date,type,locale,locale_name,description,transferred
0,NaN,Holiday,Local,NaN,NaN,False
1,NaN,Holiday,NaN,NaN,NaN,False
2,NaN,Holiday,Local,NaN,NaN,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,NaN,Holiday,Local,NaN,NaN,False
...,...,...,...,...,...,...
345,NaN,NaN,NaN,NaN,NaN,False
346,NaN,NaN,NaN,NaN,NaN,False
347,NaN,NaN,NaN,NaN,NaN,False
348,NaN,Holiday,NaN,NaN,NaN,False
349,NaN,NaN,NaN,NaN,NaN,False

#### Voltando para o roteiro, vamos iniciar outra etapa:
## Limpeza dos dados

Nesta etapa, vamos limpar os dados: corrigir tipos, tratar nulos e faltantes, incorretos, outliers e etc.

## Limpeza dos dados: Corrigir tipos

In [138]:
df.dtypes

date            str
type            str
locale          str
locale_name     str
description     str
transferred    bool
dtype: object

In [139]:
df.head(2)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False

In [140]:
date_series = pd.to_datetime(['2012-03-02', '2012-04-01', '2012-04-12', '2012-04-14', '2012-04-2'])
print(date_series)

DatetimeIndex(['2012-03-02', '2012-04-01', '2012-04-12', '2012-04-14',
               '2012-04-02'],
              dtype='datetime64[us]', freq=None)

In [141]:
df['date'] = pd.to_datetime( df['date'] )
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[us]
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[us](1), str(4)
memory usage: 14.1 KB
None

In [142]:
exemplo = pd.DataFrame(['1', '3', '5', '8'])
exemplo.dtypes

0    str
dtype: object

In [143]:
exemplo = pd.to_numeric(exemplo[0])
exemplo.dtypes

dtype('int64')

- [Mais sobre converter string para datetime.](https://www.datacamp.com/tutorial/converting-strings-datetime-objects)
- [Para quem quer entender sobre o que são tipos de dados em python e quais são eles.](https://www.datacamp.com/blog/python-data-types)
- [Lista com tipos de dados.](https://pandas.pydata.org/docs/reference/arrays.html)
- Converter para numérico: [pd.to_numeric()](https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#)

## Limpeza dos dados: Identificar nulos e faltantes

Valores marcados como NA, None, Vazio, etc. Eles irão prejudicar a análise e precisam ser corrigidos.

As estratégias para resolver esse problema podem ser resumidas em: ***deletar*** ou ***substituir***.

|Ação | Prós| Contras | Algorítimo|
|---|---|---|---|
| Deletar todas as linhas com pelo menos 1 valor nulo | Fácil, rápido, não altera o comportamento da amostra| Para bases pequenas, ou para muitos valores nulos, deletar pode prejudicar o tamanho da amostra, e leva a perda de valores não nulos.| Filtrar e deletar: `df.dropna()`|
| Substituir pela média/moda| Não há perda de dados, não altera o comportamento médio| Altera o comportamento local, pode afetar a análise| Filtrar e substituir pela média/moda da coluna: `df.fillna()` e `df.mean()`. Para dados categóricos, usar o valor mais frequente.|
| Substituir por uma nova categoria "Não informado", ou 0 | Não há perda de dados | Pode alterar o comportamento médio e local, adiciona mais uma categoria para análise| Filtrar e substituir: `df.fillna()`e `= "Não informado"`| 
|Deletar a coluna: quando há uma coluna com muitos valores nulos, pode ser vantajoso excluir ela da análise| Fácil, não interfere no comportamento geral | Se a variável for relevante para a análise, pode prejudicar o resultado| Deletar: `df.drop()`|

#### Verificando na nossa base:

In [144]:
df.isnull()

      date   type  locale  locale_name  description  transferred
0    False  False   False        False        False        False
1    False  False   False        False        False        False
2    False  False   False        False        False        False
3    False  False   False        False        False        False
4    False  False   False        False        False        False
..     ...    ...     ...          ...          ...          ...
345  False  False   False        False        False        False
346  False  False   False        False        False        False
347  False  False   False        False        False        False
348  False  False   False        False        False        False
349  False  False   False        False        False        False

[350 rows x 6 columns]

In [145]:
df.isnull().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[us]
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[us](1), str(4)
memory usage: 14.1 KB

#### Mas se tivesse nulo, o que poderiamos fazer?

Vou inserir dados nulos falsos

In [147]:
df.iloc[1] = [None, None,None,None, None, False]

In [148]:
print(df.head(3))

        date     type locale locale_name          description  transferred
0 2012-03-02  Holiday  Local       Manta   Fundacion de Manta        False
1        NaT      NaN    NaN         NaN                  NaN        False
2 2012-04-12  Holiday  Local      Cuenca  Fundacion de Cuenca        False

In [149]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         349 non-null    datetime64[us]
 1   type         349 non-null    str
 2   locale       349 non-null    str
 3   locale_name  349 non-null    str
 4   description  349 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[us](1), str(4)
memory usage: 14.1 KB
None
date           1
type           1
locale         1
locale_name    1
description    1
transferred    0
dtype: int64

In [150]:
df.dropna(axis='index', inplace=True)
# df = df.dropna(axis='index')
print(df.values)

[[Timestamp('2012-03-02 00:00:00') 'Holiday' 'Local' 'Manta'
  'Fundacion de Manta' False]
 [Timestamp('2012-04-12 00:00:00') 'Holiday' 'Local' 'Cuenca'
  'Fundacion de Cuenca' False]
 [Timestamp('2012-04-14 00:00:00') 'Holiday' 'Local' 'Libertad'
  'Cantonizacion de Libertad' False]
 ...
 [Timestamp('2017-12-24 00:00:00') 'Additional' 'National' 'Ecuador'
  'Navidad-1' False]
 [Timestamp('2017-12-25 00:00:00') 'Holiday' 'National' 'Ecuador'
  'Navidad' False]
 [Timestamp('2017-12-26 00:00:00') 'Additional' 'National' 'Ecuador'
  'Navidad+1' False]]

##### Observação: clicando na função com ctrl ou botão direito -> ver implementação

### Limpeza dos dados: linhas repetidas

In [151]:
df.duplicated()

0      False
2      False
3      False
4      False
5      False
       ...
345    False
346    False
347    False
348    False
349    False
Length: 349, dtype: bool

In [152]:
df.duplicated().sum()

np.int64(0)

> - Para deletar as duplicatas: [df.drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html)

### Limpeza dos dados: erros de escrita

In [153]:
# df.unique() # vai dar erro

In [154]:
df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='str')

In [155]:
print(df['type'].unique())
print(df['locale'].unique())
print(df['locale_name'].unique())
print(df['description'].unique())

<StringArray>
['Holiday', 'Transfer', 'Additional', 'Bridge', 'Work Day', 'Event']
Length: 6, dtype: str
<StringArray>
['Local', 'Regional', 'National']
Length: 3, dtype: str
<StringArray>
[                         'Manta',                         'Cuenca',
                       'Libertad',                       'Riobamba',
                           'Puyo',                       'Guaranda',
                       'Imbabura',                      'Latacunga',
                        'Machala',                  'Santo Domingo',
                      'El Carmen',                        'Cayambe',
                     'Esmeraldas',                        'Ecuador',
                         'Ambato',                         'Ibarra',
                        'Quevedo', 'Santo Domingo de los Tsachilas',
                    'Santa Elena',                          'Quito',
                           'Loja',                        'Salinas',
                       'Cotopaxi',                      'Guayaquil']
Length: 24, dtype: str
<StringArray>
[                    'Fundacion de Manta',
                    'Fundacion de Cuenca',
              'Cantonizacion de Libertad',
              'Cantonizacion de Riobamba',
                 'Cantonizacion del Puyo',
              'Cantonizacion de Guaranda',
          'Provincializacion de Imbabura',
             'Cantonizacion de Latacunga',
                   'Fundacion de Machala',
             'Fundacion de Santo Domingo',
 ...
                    'Terremoto Manabi+28',
                    'Terremoto Manabi+29',
                    'Terremoto Manabi+30',
          'Traslado Batalla de Pichincha',
        'Traslado Fundacion de Guayaquil',
 'Traslado Primer Grito de Independencia',
                 'Puente Dia de Difuntos',
        'Recupero Puente Dia de Difuntos',
            'Traslado Primer dia del ano',
            'Traslado Fundacion de Quito']
Length: 103, dtype: str

##### Parece que não tem nenhum erro . . .mas e se quiséssemos que tudo estivesse com letra minúscula?

In [156]:
df['type'].str.lower()

0         holiday
2         holiday
3         holiday
4         holiday
5         holiday
          ...
345    additional
346    additional
347    additional
348       holiday
349    additional
Name: type, Length: 349, dtype: str

##### E para fazer para todos os campos?

In [157]:
# df.columns
campos_categoricos = ['type', 'locale', 'locale_name', 'description']
for campo in campos_categoricos:
    print(campo)
    df[campo] = df[campo].str.lower()
    print(df[campo].unique())
    print('')

type
<StringArray>
['holiday', 'transfer', 'additional', 'bridge', 'work day', 'event']
Length: 6, dtype: str

locale
<StringArray>
['local', 'regional', 'national']
Length: 3, dtype: str

locale_name
<StringArray>
[                         'manta',                         'cuenca',
                       'libertad',                       'riobamba',
                           'puyo',                       'guaranda',
                       'imbabura',                      'latacunga',
                        'machala',                  'santo domingo',
                      'el carmen',                        'cayambe',
                     'esmeraldas',                        'ecuador',
                         'ambato',                         'ibarra',
                        'quevedo', 'santo domingo de los tsachilas',
                    'santa elena',                          'quito',
                           'loja',                        'salinas',
                       'cotopaxi',                      'guayaquil']
Length: 24, dtype: str

description
<StringArray>
[                    'fundacion de manta',
                    'fundacion de cuenca',
              'cantonizacion de libertad',
              'cantonizacion de riobamba',
                 'cantonizacion del puyo',
              'cantonizacion de guaranda',
          'provincializacion de imbabura',
             'cantonizacion de latacunga',
                   'fundacion de machala',
             'fundacion de santo domingo',
 ...
                    'terremoto manabi+28',
                    'terremoto manabi+29',
                    'terremoto manabi+30',
          'traslado batalla de pichincha',
        'traslado fundacion de guayaquil',
 'traslado primer grito de independencia',
                 'puente dia de difuntos',
        'recupero puente dia de difuntos',
            'traslado primer dia del ano',
            'traslado fundacion de quito']
Length: 101, dtype: str

#### Caso queira corrigir palavras ou alterar nomes:

In [158]:
df.replace('holiday', 'férias', inplace=True)
print(df['type'].unique())

<StringArray>
['férias', 'transfer', 'additional', 'bridge', 'work day', 'event']
Length: 6, dtype: str

### Limpeza de dados: Outliers

Outliers são dados que fogem a norma. Dados que são tão diferentes que podem prejudicar a análise.
Vamos entender eles mais tarde, depois de aprendermos a fazer análise visual e estatística descritiva.

## Atividade

### Tratamento dos dados\atividade_02.ipynb

### Atividades Extras 
1. Substitua todas as palavras em inglês no campo 'type' por suas traduções para o português. Use um loop para agilizr a substituição

```
ingles = ['holiday', 'transfer', 'additional', 'bridge', 'work day', 'event']`
traducao = ['férias', 'transferência', 'adicional', 'ponte', 'dia útil', 'evento']
```

2. Substitua todos os valores booleanos do campo 'transfered' for 0 e 1, para `False` e `True`, respectivamente.